/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.97
 * Generated at: 2024-01-12 12:32:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.5.30.jar", Long.valueOf(1703843042348L));
    _jspx_dependants.put("jar:file:/C:/Users/anvar/Desktop/Project/job/JOB/public_html/WEB-INF/lib/struts2-core-2.5.30.jar!/META-INF/struts-tags.tld", Long.valueOf(1647332392000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <style>\r\n");
      out.write("    .nav-item:hover{\r\n");
      out.write("    background-color:#454545;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    </style>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("    $('#featuresDropdown').mouseover(function(){\r\n");
      out.write("        $(this).addClass('show');\r\n");
      out.write("        $(this).find('a').attr('aria-expanded', true);\r\n");
      out.write("        $(this).find(' ul').addClass('show');\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    $('#featuresDropdown').mouseout(function(){\r\n");
      out.write("        $(this).removeClass('show');\r\n");
      out.write("        $(this).find(' a').attr('aria-expanded', false);\r\n");
      out.write("        $(this).find(' ul').removeClass('show');\r\n");
      out.write("    });\r\n");
      out.write("    $('#tools').mouseover(function(){\r\n");
      out.write("        $(this).addClass('show');\r\n");
      out.write("        $(this).find('a').attr('aria-expanded', true);\r\n");
      out.write("        $(this).find(' ul').addClass('show');\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    $('#tools').mouseout(function(){\r\n");
      out.write("        $(this).removeClass('show');\r\n");
      out.write("        $(this).find(' a').attr('aria-expanded', false);\r\n");
      out.write("        $(this).find(' ul').removeClass('show');\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("  \r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("    </head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"bootstrap-container\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-light \" id=\"navColor\" style=\"background-color: green;\">\r\n");
      out.write("       <div class=\"container-fluid\">\r\n");
      out.write("       <a class=\"navbar-brand\"\r\n");
      out.write("                style=\"color: white; letter-spacing: 5px; border-radius: 25px; margin-right: 15px;\">JPS</a>\r\n");
      out.write("    \r\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("              <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("               \r\n");
      out.write("                <li class=\"nav-item dropdown\" id=\"featuresDropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle p-2 rounded text-white\"  role=\"button\"\r\n");
      out.write("                        data-bs-toggle=\"dropdown\" style=\"background-color: #454545;\">\r\n");
      out.write("                        ");
      if (_jspx_meth_s_005ftext_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                        <li><a class=\"dropdown-item\"  role=\"button\" onclick=\"searchPages()\">");
      if (_jspx_meth_s_005ftext_005f1(_jspx_page_context))
        return;
      out.write("</a></li>\r\n");
      out.write("                        \r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<ul class=\"nav\">\r\n");
      out.write("\r\n");
      out.write("				\r\n");
      out.write("       <li class=\"nav-item dropdown\" id=\"tools\">\r\n");
      out.write("      <a class=\"nav-link active dropdown-toggle\" role=\"button\" title=\"tools\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("         <i class=\"fa-solid fa-wrench fa-beat text-white\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("      <ul class=\"dropdown-menu\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("         <li class=\"nav-items dropdown\" id=\"menud\"><a role=\"button\">\r\n");
      out.write("            <i class=\"fa fa-plus-square\">&nbsp</i>");
      if (_jspx_meth_s_005ftext_005f2(_jspx_page_context))
        return;
      out.write("</a>\r\n");
      out.write("            <div style=\"display:none\" class=\"menu\">\r\n");
      out.write("               <ul style=\"list-style: none;\">\r\n");
      out.write("                \r\n");
      out.write("				<li><a onmouseover=\"changeNavBarColor('#0171c7')\" role=\"button\" style=\"color:#0171c7\"><i class=\"fa-solid fa-circle\">&nbsp</i>");
      if (_jspx_meth_s_005ftext_005f3(_jspx_page_context))
        return;
      out.write("</a></li>\r\n");
      out.write("				<li><a onmouseover=\"changeNavBarColor('#585858')\" role=\"button\" style=\"color:#585858\"><i class=\"fa-solid fa-circle\">&nbsp</i>");
      if (_jspx_meth_s_005ftext_005f4(_jspx_page_context))
        return;
      out.write("</a></li>\r\n");
      out.write(" 				<li><a onmouseover=\"changeNavBarColor('green')\" role=\"button\" style=\"color:green\"><i class=\"fa-solid fa-circle\">&nbsp </i>");
      if (_jspx_meth_s_005ftext_005f5(_jspx_page_context))
        return;
      out.write("</a></li>\r\n");
      out.write(" 				<li><a onmouseover=\"changeNavBarColor('teal')\" role=\"button\" style=\"color:teal\"><i class=\"fa-solid fa-circle\">&nbsp </i>");
      if (_jspx_meth_s_005ftext_005f6(_jspx_page_context))
        return;
      out.write("</a></li>\r\n");
      out.write("               </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("         </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("   </li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"nav-item\"><a class=\"nav-link active\" title=\"tools\"href=\"home\"><i class=\"fas fa-home text-white\"></i></a>\r\n");
      out.write("							</li>\r\n");
      out.write("						<li class=\"nav-item\"><a title=\"mail\" href=\"mailto:your-email@jps.com\"\r\n");
      out.write("							class=\"nav-link\"> <i class=\"fas fa-envelope text-white\"></i>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li class=\"nav-item\"><a title=\"sign-out\" class=\"nav-link\" href=\"signOut\"><i\r\n");
      out.write("								class=\"fas fa-sign-out-alt text-white\"></i></a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("		\r\n");
      out.write("				\r\n");
      out.write("			\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_s_005ftext_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f0 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    boolean _jspx_th_s_005ftext_005f0_reused = false;
    try {
      _jspx_th_s_005ftext_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f0.setParent(null);
      // /pages/Header.jsp(67,24) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f0.setName("features.header");
      int _jspx_eval_s_005ftext_005f0 = _jspx_th_s_005ftext_005f0.doStartTag();
      if (_jspx_th_s_005ftext_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f0);
      _jspx_th_s_005ftext_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005ftext_005f0, _jsp_getInstanceManager(), _jspx_th_s_005ftext_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f1 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    boolean _jspx_th_s_005ftext_005f1_reused = false;
    try {
      _jspx_th_s_005ftext_005f1.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f1.setParent(null);
      // /pages/Header.jsp(70,92) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f1.setName("jobsearch.message");
      int _jspx_eval_s_005ftext_005f1 = _jspx_th_s_005ftext_005f1.doStartTag();
      if (_jspx_th_s_005ftext_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f1);
      _jspx_th_s_005ftext_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005ftext_005f1, _jsp_getInstanceManager(), _jspx_th_s_005ftext_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f2 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    boolean _jspx_th_s_005ftext_005f2_reused = false;
    try {
      _jspx_th_s_005ftext_005f2.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f2.setParent(null);
      // /pages/Header.jsp(88,50) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f2.setName("themes.header");
      int _jspx_eval_s_005ftext_005f2 = _jspx_th_s_005ftext_005f2.doStartTag();
      if (_jspx_th_s_005ftext_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f2);
      _jspx_th_s_005ftext_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005ftext_005f2, _jsp_getInstanceManager(), _jspx_th_s_005ftext_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f3 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    boolean _jspx_th_s_005ftext_005f3_reused = false;
    try {
      _jspx_th_s_005ftext_005f3.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f3.setParent(null);
      // /pages/Header.jsp(92,129) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f3.setName("blue");
      int _jspx_eval_s_005ftext_005f3 = _jspx_th_s_005ftext_005f3.doStartTag();
      if (_jspx_th_s_005ftext_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f3);
      _jspx_th_s_005ftext_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005ftext_005f3, _jsp_getInstanceManager(), _jspx_th_s_005ftext_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f4 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    boolean _jspx_th_s_005ftext_005f4_reused = false;
    try {
      _jspx_th_s_005ftext_005f4.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f4.setParent(null);
      // /pages/Header.jsp(93,129) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f4.setName("grey");
      int _jspx_eval_s_005ftext_005f4 = _jspx_th_s_005ftext_005f4.doStartTag();
      if (_jspx_th_s_005ftext_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f4);
      _jspx_th_s_005ftext_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005ftext_005f4, _jsp_getInstanceManager(), _jspx_th_s_005ftext_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f5 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    boolean _jspx_th_s_005ftext_005f5_reused = false;
    try {
      _jspx_th_s_005ftext_005f5.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f5.setParent(null);
      // /pages/Header.jsp(94,127) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f5.setName("green");
      int _jspx_eval_s_005ftext_005f5 = _jspx_th_s_005ftext_005f5.doStartTag();
      if (_jspx_th_s_005ftext_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f5);
      _jspx_th_s_005ftext_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005ftext_005f5, _jsp_getInstanceManager(), _jspx_th_s_005ftext_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f6 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    boolean _jspx_th_s_005ftext_005f6_reused = false;
    try {
      _jspx_th_s_005ftext_005f6.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f6.setParent(null);
      // /pages/Header.jsp(95,125) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f6.setName("teal");
      int _jspx_eval_s_005ftext_005f6 = _jspx_th_s_005ftext_005f6.doStartTag();
      if (_jspx_th_s_005ftext_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f6);
      _jspx_th_s_005ftext_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005ftext_005f6, _jsp_getInstanceManager(), _jspx_th_s_005ftext_005f6_reused);
    }
    return false;
  }
}
