/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.97
 * Generated at: 2024-01-15 12:25:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class JobList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.5.30.jar", Long.valueOf(1703843042348L));
    _jspx_dependants.put("jar:file:/C:/Users/anvar/Desktop/Project/job/JOB/public_html/WEB-INF/lib/struts2-core-2.5.30.jar!/META-INF/struts-tags.tld", Long.valueOf(1647332392000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005factionmessage_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005felse;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005factionmessage_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005felse = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fs_005factionmessage_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005felse.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" <!--JobList.jsp :- the jsp display the details of job in jqGrid -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/themes/redmond/jquery-ui.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/free-jqgrid/4.15.5/css/ui.jqgrid.min.css\">\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/free-jqgrid/4.15.5/jquery.jqgrid.min.js\"></script>\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\" integrity=\"sha384-Ze5zAaV5Vt9zK6QzjOPrOv+g0TRjD5VmzapR5C2S66O4TKNp1Ch1XWL0GLwOcjBO\" crossorigin=\"anonymous\">\r\n");
      out.write("   <style>\r\n");
      out.write("    #jqGrid_toppager {\r\n");
      out.write("        height: 50px; \r\n");
      out.write("       \r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   .ui-widget-content {\r\n");
      out.write("   color:black ;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ui-jqgrid .ui-pg-table {\r\n");
      out.write("    background-color: white	; \r\n");
      out.write("	color:black !important;\r\n");
      out.write("    }\r\n");
      out.write("   \r\n");
      out.write("      .fa-file-pdf {\r\n");
      out.write("        color: red !important;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .fa-file-excel {\r\n");
      out.write("        color: green !important;\r\n");
      out.write("    }\r\n");
      out.write("    .fa-html5 {\r\n");
      out.write("     color: #0171c7 !important;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .fa-eye {\r\n");
      out.write("        color: blue !important;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("</style>\r\n");
      out.write("    <script>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    function confirmDelete(deleteLink) {\r\n");
      out.write("        if (window.confirm(\"Are you sure you want to delete this record?\")) {\r\n");
      out.write("        	 $('body').append('<div class=\"overlay\"><div class=\"loading\"><img src=\"./images/proload.gif\" alt=\"\"> Loading Content</div></div>');\r\n");
      out.write("	        	$.ajax({\r\n");
      out.write("                url: deleteLink,\r\n");
      out.write("                method: 'POST',\r\n");
      out.write("                success: function (data) {\r\n");
      out.write("                	$('.overlay').remove();\r\n");
      out.write("                    $('#content').html(data);\r\n");
      out.write("\r\n");
      out.write("                },\r\n");
      out.write("                error: function (error) {\r\n");
      out.write("                    console.error('Error fetching data:', error);\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("   	 }\r\n");
      out.write("    \r\n");
      out.write("    function downloadReport(JobID) {\r\n");
      out.write("   	    var selectedLanguage = $('#languages').val()\r\n");
      out.write("    	var downloadUrl = 'reportDownload?jobId=' + JobID + '&language='+selectedLanguage+'&reportType=pdf';\r\n");
      out.write("        var downloadLink = document.createElement('a');\r\n");
      out.write("        downloadLink.href = downloadUrl;\r\n");
      out.write("        downloadLink.target = '_blank';  \r\n");
      out.write("        downloadLink.download = 'jasperReports.pdf';\r\n");
      out.write("\r\n");
      out.write("        document.body.appendChild(downloadLink);\r\n");
      out.write("\r\n");
      out.write("        downloadLink.click();\r\n");
      out.write("\r\n");
      out.write("        document.body.removeChild(downloadLink);\r\n");
      out.write("        \r\n");
      out.write("    }\r\n");
      out.write("  \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    function downloadXlsReport(JobID) {\r\n");
      out.write("   	    var selectedLanguage = $('#languages').val()\r\n");
      out.write("        var downloadUrl = 'reportDownload?jobId=' + JobID + '&language=' + selectedLanguage +'&reportType=excel';\r\n");
      out.write("\r\n");
      out.write("    	var downloadLink = document.createElement('a');\r\n");
      out.write("        downloadLink.href = downloadUrl;\r\n");
      out.write("        downloadLink.target = '_blank';  \r\n");
      out.write("        downloadLink.download = 'jasperReport.xlsx';\r\n");
      out.write("\r\n");
      out.write("        document.body.appendChild(downloadLink);\r\n");
      out.write("\r\n");
      out.write("        downloadLink.click();\r\n");
      out.write("\r\n");
      out.write("        document.body.removeChild(downloadLink);\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("    function downloadHtmlReport(JobID) {\r\n");
      out.write("   	    var selectedLanguage = $('#languages').val()\r\n");
      out.write("        var downloadUrl = 'reportDownload?jobId=' + JobID + '&language=' + selectedLanguage +'&reportType=html';\r\n");
      out.write("\r\n");
      out.write("    	var downloadLink = document.createElement('a');\r\n");
      out.write("        downloadLink.href = downloadUrl;\r\n");
      out.write("        downloadLink.target = '_blank';  \r\n");
      out.write("        downloadLink.download = 'jasperReport.html';\r\n");
      out.write("\r\n");
      out.write("        document.body.appendChild(downloadLink);\r\n");
      out.write("\r\n");
      out.write("        downloadLink.click();\r\n");
      out.write("\r\n");
      out.write("        document.body.removeChild(downloadLink);\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function editPage(editPageLink){\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            url: editPageLink,\r\n");
      out.write("            method: 'POST',\r\n");
      out.write("            success: function (data) {\r\n");
      out.write("                $('#content').html(data);\r\n");
      out.write("\r\n");
      out.write("            },\r\n");
      out.write("            error: function (error) {\r\n");
      out.write("                console.error('Error fetching data:', error);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("    function viewPage(viewPageLink){\r\n");
      out.write("    	$('body').append('<div class=\"overlay\"><div class=\"loading  gap-2\"><img src=\"./images/proload.gif\" alt=\"\"> Loading Content . .  </div></div>');\r\n");
      out.write("\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            url: viewPageLink,\r\n");
      out.write("            method: 'POST',\r\n");
      out.write("            success: function (data) {\r\n");
      out.write("            	$('.overlay').remove();\r\n");
      out.write("                $('#content').html(data);\r\n");
      out.write("\r\n");
      out.write("            },\r\n");
      out.write("            error: function (error) {\r\n");
      out.write("                console.error('Error fetching data:', error);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("    </head>\r\n");
      out.write("    \r\n");
      out.write("<body>\r\n");
      out.write("	\r\n");
      out.write("	<div style=\"margin-bottom: 5px; border-bottom: 5px solid green;\">\r\n");
      out.write("		<h2 class=\"mt-2\">");
      if (_jspx_meth_s_005ftext_005f0(_jspx_page_context))
        return;
      out.write("</h2>\r\n");
      out.write("	</div>\r\n");
      out.write("	 ");
      if (_jspx_meth_s_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("<div class=\"d-flex flex-row align-items-center gap-2\">\r\n");
      out.write("\r\n");
      if (_jspx_meth_s_005fif_005f1(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_s_005felse_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write(" \r\n");
      out.write("    \r\n");
      out.write("    <select id=\"languages\" class=\"form-select\" style=\"width:100px\">\r\n");
      out.write("        <option value=\"en\">English</option>\r\n");
      out.write("        <option value=\"fr\">French</option>\r\n");
      out.write("    </select>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("	<br>\r\n");
      out.write("	\r\n");
      out.write("    <table id=\"jqGrid\" ></table>\r\n");
      out.write("    <div id=\"jqGridPager\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        $(document).ready(function () {\r\n");
      out.write("            var jobListJson = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${model.jobListJson}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("            console.log(jobListJson);\r\n");
      out.write("            $(\"#jqGrid\").jqGrid({\r\n");
      out.write("                datatype: \"local\",\r\n");
      out.write("                data: jobListJson,\r\n");
      out.write("                colModel:[ { name: 'rn', label: 'SI', width: 50, align: 'center', sortable: false, search: false, resizable: false },\r\n");
      out.write("                	  { name: 'jobId', label: 'Job ID', hidden: true }, \r\n");
      out.write("                	    { label: 'Job Title', name: 'jobTitle', width: 200, searchoptions: { sopt: ['eq', 'ne', 'cn'] } },\r\n");
      out.write("                	    { label: 'Company Name', name: 'cmpName', width: 100, searchoptions: { sopt: ['eq', 'ne', 'cn'] } },\r\n");
      out.write("                	    { label: 'Skills', name: 'skills', width: 100, searchoptions: { sopt: ['eq', 'ne', 'cn'] } },\r\n");
      out.write("                	    { label: 'Location', name: 'locations', width: 100, searchoptions: { sopt: ['eq', 'ne', 'cn'] } },\r\n");
      out.write("                	    { label: 'Company Website', name: 'cmpWebsite', width: 150, searchoptions: { sopt: ['eq', 'ne', 'cn'] } },\r\n");
      out.write("                	    { label: 'Experience', name: 'experience', width: 150, searchoptions: { sopt: ['eq','cn'] } },\r\n");
      out.write("                	    { label: 'CTC From', name: 'ctcFrom', width: 150, searchoptions: { sopt: ['eq','cn'] } },\r\n");
      out.write("                	    { label: 'CTC to', name: 'ctcTo', width: 150, searchoptions: { sopt: ['eq','cn'] } },\r\n");
      out.write("                	    { label: 'Job Level', name: 'jobLevel', width: 150, searchoptions: { sopt: ['eq', 'ne', 'cn'] } },\r\n");
      out.write("                	    { label: 'Job Type', name: 'jobType', width: 150, searchoptions: { sopt: ['eq', 'ne', 'cn'] } },\r\n");
      out.write("                	   { label: 'Posting Date', name: 'postingDate', width: 150 ,\r\n");
      out.write("                    	formatoptions : {newformat : \"d-M-Y\"},searchoptions : {sopt : [ 'eq' ]}},\r\n");
      out.write("                    {\r\n");
      out.write("                        label: 'Edit',\r\n");
      out.write("                        name: 'edit',\r\n");
      out.write("                        width: 150,\r\n");
      out.write("                        formatter: function (cellValue, options, rowObject) {\r\n");
      out.write("                            var JobID = rowObject.jobId;\r\n");
      out.write("                            var editPageLink = 'toEditPage?jobId=' + JobID ;\r\n");
      out.write("                            return '<a class=\"btn\" onclick=\"editPage(\\'' + editPageLink + '\\')\"><i class=\"fas fa-pen \"></i></a>';\r\n");
      out.write("\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                    },\r\n");
      out.write("                    {\r\n");
      out.write("                        label: 'Delete',\r\n");
      out.write("                        name: 'delete',\r\n");
      out.write("                        width: 150,\r\n");
      out.write("                        formatter: function (cellValue, options, rowObject) {\r\n");
      out.write("                            var JobID = rowObject.jobId;\r\n");
      out.write("                            var deleteLink = 'jobDelete?jobId=' + JobID;\r\n");
      out.write("                            return '<a class=\"btn\"  onclick=\"confirmDelete(\\'' + deleteLink + '\\')\"><i class=\"fas fa-trash-alt \"></i></a>';\r\n");
      out.write("                        }\r\n");
      out.write("                    },\r\n");
      out.write("                    \r\n");
      out.write("                ],\r\n");
      out.write("                rowList: [5, 10, 20],\r\n");
      out.write("                viewrecords: true,\r\n");
      out.write("                autowidth: true,\r\n");
      out.write("                rowNum: 5,\r\n");
      out.write("                toppager:true,\r\n");
      out.write("				iconSet:'fontAwesome',\r\n");
      out.write("                pager: \"#jqGridPager\",\r\n");
      out.write("              \r\n");
      out.write("            });\r\n");
      out.write("            $(\"#jqGrid\").jqGrid('navGrid', '#jqGrid_toppager', { edit: false, add: false, del: false, search: true });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("          	 \r\n");
      out.write("            $(\"#jqGrid\").jqGrid('navButtonAdd', '#jqGrid_toppager', {\r\n");
      out.write("                caption: '',\r\n");
      out.write("                title: \"View\",\r\n");
      out.write("                buttonicon: \"fa-solid fa-eye fa-beat-fade\",\r\n");
      out.write("                onClickButton: function () {\r\n");
      out.write("                    var selectedRowId = $(\"#jqGrid\").jqGrid('getGridParam', 'selrow');\r\n");
      out.write("\r\n");
      out.write("                    if (selectedRowId) {\r\n");
      out.write("                        var selectedRowData = $(\"#jqGrid\").jqGrid('getRowData', selectedRowId);\r\n");
      out.write("                        var jobID = selectedRowData.jobId;\r\n");
      out.write("                        var viewPageLink = 'viewPages?jobId=' + jobID ;\r\n");
      out.write("                        viewPage(viewPageLink);\r\n");
      out.write("                    } else {\r\n");
      out.write("                        alert('Please select a row to view.');\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                \r\n");
      out.write("            });\r\n");
      out.write("            $(\"#jqGrid\").jqGrid('navButtonAdd', '#jqGrid_toppager', {\r\n");
      out.write("                caption: '',\r\n");
      out.write("                title: \"pdf\",\r\n");
      out.write("                buttonicon: \"fa-regular fa-file-pdf fa-beat\",\r\n");
      out.write("                onClickButton: function () {\r\n");
      out.write("                    var selectedRowId = $(\"#jqGrid\").jqGrid('getGridParam', 'selrow');\r\n");
      out.write("\r\n");
      out.write("                    if (selectedRowId) {\r\n");
      out.write("                        var selectedRowData = $(\"#jqGrid\").jqGrid('getRowData', selectedRowId);\r\n");
      out.write("                        var jobID = selectedRowData.jobId;\r\n");
      out.write("                        downloadReport(jobID);\r\n");
      out.write("                    } else {\r\n");
      out.write("                        alert('Please select a row to download pdf.');\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                \r\n");
      out.write("            });\r\n");
      out.write("            $(\"#jqGrid\").jqGrid('navButtonAdd', '#jqGrid_toppager', {\r\n");
      out.write("                caption: '',\r\n");
      out.write("                title: \"excel\",\r\n");
      out.write("                buttonicon: \"fa-regular fa-file-excel fa-beat-fade\",\r\n");
      out.write("                onClickButton: function () {\r\n");
      out.write("                    var selectedRowId = $(\"#jqGrid\").jqGrid('getGridParam', 'selrow');\r\n");
      out.write("\r\n");
      out.write("                    if (selectedRowId) {\r\n");
      out.write("                        var selectedRowData = $(\"#jqGrid\").jqGrid('getRowData', selectedRowId);\r\n");
      out.write("                        var jobID = selectedRowData.jobId;\r\n");
      out.write("                        downloadXlsReport(jobID);\r\n");
      out.write("                    } else {\r\n");
      out.write("                        alert('Please select a row to download excel.');\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                \r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("            $(\"#jqGrid\").jqGrid('navButtonAdd', '#jqGrid_toppager', {\r\n");
      out.write("                caption: '',\r\n");
      out.write("                title: \"html\",\r\n");
      out.write("                buttonicon: \"fa-brands fa-html5 fa-beat fa-flip\",\r\n");
      out.write("                onClickButton: function () {\r\n");
      out.write("                    var selectedRowId = $(\"#jqGrid\").jqGrid('getGridParam', 'selrow');\r\n");
      out.write("\r\n");
      out.write("                    if (selectedRowId) {\r\n");
      out.write("                        var selectedRowData = $(\"#jqGrid\").jqGrid('getRowData', selectedRowId);\r\n");
      out.write("                        var jobID = selectedRowData.jobId;\r\n");
      out.write("                        downloadHtmlReport(jobID);\r\n");
      out.write("                    } else {\r\n");
      out.write("                        alert('Please select a row to download html.');\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                \r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("  \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_s_005ftext_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f0 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    boolean _jspx_th_s_005ftext_005f0_reused = false;
    try {
      _jspx_th_s_005ftext_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f0.setParent(null);
      // /JobList.jsp(159,19) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f0.setName("JobList");
      int _jspx_eval_s_005ftext_005f0 = _jspx_th_s_005ftext_005f0.doStartTag();
      if (_jspx_th_s_005ftext_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f0);
      _jspx_th_s_005ftext_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005ftext_005f0, _jsp_getInstanceManager(), _jspx_th_s_005ftext_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:if
    org.apache.struts2.views.jsp.IfTag _jspx_th_s_005fif_005f0 = (org.apache.struts2.views.jsp.IfTag) _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.get(org.apache.struts2.views.jsp.IfTag.class);
    boolean _jspx_th_s_005fif_005f0_reused = false;
    try {
      _jspx_th_s_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005fif_005f0.setParent(null);
      // /JobList.jsp(161,2) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fif_005f0.setTest("hasActionMessages()");
      int _jspx_eval_s_005fif_005f0 = _jspx_th_s_005fif_005f0.doStartTag();
      if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_s_005fif_005f0);
        }
        do {
          out.write("\r\n");
          out.write("				<div class=\"alert alert-warning alert-dismissible fade show\"\r\n");
          out.write("					role=\"alert\">\r\n");
          out.write("					<h4>");
          if (_jspx_meth_s_005ftext_005f1(_jspx_th_s_005fif_005f0, _jspx_page_context))
            return true;
          out.write(" !</h4>\r\n");
          out.write("					");
          if (_jspx_meth_s_005factionmessage_005f0(_jspx_th_s_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("					<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\"\r\n");
          out.write("						aria-label=\"Close\"></button>\r\n");
          out.write("				</div>\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_s_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_s_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.reuse(_jspx_th_s_005fif_005f0);
      _jspx_th_s_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_s_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f1 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    boolean _jspx_th_s_005ftext_005f1_reused = false;
    try {
      _jspx_th_s_005ftext_005f1.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fif_005f0);
      // /JobList.jsp(164,9) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f1.setName("success");
      int _jspx_eval_s_005ftext_005f1 = _jspx_th_s_005ftext_005f1.doStartTag();
      if (_jspx_th_s_005ftext_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f1);
      _jspx_th_s_005ftext_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005ftext_005f1, _jsp_getInstanceManager(), _jspx_th_s_005ftext_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005factionmessage_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:actionmessage
    org.apache.struts2.views.jsp.ui.ActionMessageTag _jspx_th_s_005factionmessage_005f0 = (org.apache.struts2.views.jsp.ui.ActionMessageTag) _005fjspx_005ftagPool_005fs_005factionmessage_005fnobody.get(org.apache.struts2.views.jsp.ui.ActionMessageTag.class);
    boolean _jspx_th_s_005factionmessage_005f0_reused = false;
    try {
      _jspx_th_s_005factionmessage_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005factionmessage_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fif_005f0);
      int _jspx_eval_s_005factionmessage_005f0 = _jspx_th_s_005factionmessage_005f0.doStartTag();
      if (_jspx_th_s_005factionmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005factionmessage_005fnobody.reuse(_jspx_th_s_005factionmessage_005f0);
      _jspx_th_s_005factionmessage_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005factionmessage_005f0, _jsp_getInstanceManager(), _jspx_th_s_005factionmessage_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:if
    org.apache.struts2.views.jsp.IfTag _jspx_th_s_005fif_005f1 = (org.apache.struts2.views.jsp.IfTag) _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.get(org.apache.struts2.views.jsp.IfTag.class);
    boolean _jspx_th_s_005fif_005f1_reused = false;
    try {
      _jspx_th_s_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_s_005fif_005f1.setParent(null);
      // /JobList.jsp(173,0) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fif_005f1.setTest("actionName == 'home'");
      int _jspx_eval_s_005fif_005f1 = _jspx_th_s_005fif_005f1.doStartTag();
      if (_jspx_eval_s_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_s_005fif_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_s_005fif_005f1);
        }
        do {
          out.write("\r\n");
          out.write(" <a class=\"btn btn-secondary mt-4 mb-4\" href=\"home\">");
          if (_jspx_meth_s_005ftext_005f2(_jspx_th_s_005fif_005f1, _jspx_page_context))
            return true;
          out.write("</a>\r\n");
          int evalDoAfterBody = _jspx_th_s_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_s_005fif_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_s_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.reuse(_jspx_th_s_005fif_005f1);
      _jspx_th_s_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_s_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f2 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    boolean _jspx_th_s_005ftext_005f2_reused = false;
    try {
      _jspx_th_s_005ftext_005f2.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fif_005f1);
      // /JobList.jsp(174,52) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f2.setName("back.button");
      int _jspx_eval_s_005ftext_005f2 = _jspx_th_s_005ftext_005f2.doStartTag();
      if (_jspx_th_s_005ftext_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f2);
      _jspx_th_s_005ftext_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005ftext_005f2, _jsp_getInstanceManager(), _jspx_th_s_005ftext_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005felse_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:else
    org.apache.struts2.views.jsp.ElseTag _jspx_th_s_005felse_005f0 = (org.apache.struts2.views.jsp.ElseTag) _005fjspx_005ftagPool_005fs_005felse.get(org.apache.struts2.views.jsp.ElseTag.class);
    boolean _jspx_th_s_005felse_005f0_reused = false;
    try {
      _jspx_th_s_005felse_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005felse_005f0.setParent(null);
      int _jspx_eval_s_005felse_005f0 = _jspx_th_s_005felse_005f0.doStartTag();
      if (_jspx_eval_s_005felse_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_s_005felse_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_s_005felse_005f0);
        }
        do {
          out.write("\r\n");
          out.write("   <a class=\"btn btn-secondary mt-4 mb-4\" onclick=\"searchPages()\">");
          if (_jspx_meth_s_005ftext_005f3(_jspx_th_s_005felse_005f0, _jspx_page_context))
            return true;
          out.write("</a>\r\n");
          int evalDoAfterBody = _jspx_th_s_005felse_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_s_005felse_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_s_005felse_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005felse.reuse(_jspx_th_s_005felse_005f0);
      _jspx_th_s_005felse_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005felse_005f0, _jsp_getInstanceManager(), _jspx_th_s_005felse_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005felse_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f3 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    boolean _jspx_th_s_005ftext_005f3_reused = false;
    try {
      _jspx_th_s_005ftext_005f3.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005felse_005f0);
      // /JobList.jsp(177,66) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f3.setName("back.button");
      int _jspx_eval_s_005ftext_005f3 = _jspx_th_s_005ftext_005f3.doStartTag();
      if (_jspx_th_s_005ftext_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f3);
      _jspx_th_s_005ftext_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005ftext_005f3, _jsp_getInstanceManager(), _jspx_th_s_005ftext_005f3_reused);
    }
    return false;
  }
}
